# Generated by Django 4.0 on 2022-07-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0001_initial'),
        ('autenticacion', '0003_alter_organizacion_tipo_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idSabor', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameSabor', models.CharField(max_length=64, verbose_name='Sabor')),
                ('nivelSabor', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1)),
                ('pI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IPSabor', to='analisis.sabor', verbose_name='Padre Nivel I')),
                ('pII', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IIPSabor', to='analisis.sabor', verbose_name='Padre Nivel II')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('idMuestra', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Lote')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('fechaEntrega', models.DateField()),
                ('peso', models.CharField(choices=[('100', '100'), ('300', '300'), ('350', '350'), ('500', '500')], default='100', max_length=4)),
                ('tipo', models.IntegerField(choices=[(1, 'Cafe Pergamino'), (2, 'Cafe Oro')], verbose_name='Tipo de Muestra')),
                ('caracteristicas', models.IntegerField(choices=[(1, 'Derrame'), (2, 'Olor no característico'), (3, 'Empaque roto'), (4, 'Buen estado')], verbose_name='Caracteristicas')),
                ('rMuestra', models.IntegerField(default=0)),
                ('procesos', models.IntegerField(choices=[(1, 'Fisico'), (2, 'Sensorial'), (3, 'Ambos')], verbose_name='Procesos a aplicar')),
                ('observaciones', models.TextField(blank=True, max_length=254, verbose_name='Observaciones')),
                ('estado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente'), (3, 'En Proceso')], default=2)),
                ('analizado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente'), (3, 'En Proceso')], default=2)),
                ('fkLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Muestras', to='registros.lote', verbose_name='Lote')),
                ('fkOrg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrgMuestra', to='autenticacion.organizacion', verbose_name='Organización')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idAroma', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameAroma', models.CharField(max_length=64, verbose_name='Aroma')),
                ('nivelAroma', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1)),
                ('pI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IPAroma', to='analisis.aroma', verbose_name='Padre Nivel I')),
                ('pII', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IIPAroma', to='analisis.aroma', verbose_name='Padre Nivel II')),
                ('pIII', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IIIPAroma', to='analisis.aroma', verbose_name='Padre Nivel III')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
