# Generated by Django 4.0 on 2022-08-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_organizacion_tipo_org'),
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectoT1',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idDefecto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameDefecto', models.CharField(max_length=64, verbose_name='Defecto')),
                ('granosNecesarios', models.IntegerField(verbose_name='Granos Necesarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectoT2',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idDefecto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameDefecto', models.CharField(max_length=64, verbose_name='Defecto')),
                ('granosNecesarios', models.IntegerField(verbose_name='Granos Necesarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('pDefectos', models.FloatField(blank=True, default=0.0)),
                ('pRendimiento', models.FloatField(blank=True, default=0.0)),
                ('pMancha', models.FloatField(blank=True, default=0.0)),
                ('pBroca', models.FloatField(blank=True, default=0.0)),
                ('fechaFisico', models.DateField(auto_now_add=True)),
                ('fkCatador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatadorFisico', to='autenticacion.colaborador', verbose_name='CatadorFisico')),
                ('fkMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fsico', to='analisis.muestra', verbose_name='Muestra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FisicoDefectoTII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('encontrados', models.IntegerField(default=0)),
                ('defectos', models.IntegerField(default=0)),
                ('pesoDefecto', models.FloatField(blank=True, default=0.0)),
                ('porDefecto', models.FloatField(blank=True, default=0.0)),
                ('fkDefecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DefectoT2', to='analisis.defectot2', verbose_name='Defecto')),
                ('fkFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FisicoDefectoTII', to='analisis.fisico', verbose_name='Fisico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FisicoDefectoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('encontrados', models.IntegerField(default=0)),
                ('defectos', models.IntegerField(default=0)),
                ('pesoDefecto', models.FloatField(blank=True, default=0.0)),
                ('porDefecto', models.FloatField(blank=True, default=0.0)),
                ('fkDefecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DefectoT1', to='analisis.defectot1', verbose_name='Defecto')),
                ('fkFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FisicoDefectoTI', to='analisis.fisico', verbose_name='Fisico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
