# Generated by Django 4.0 on 2022-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_defectot1_defectot2_fisico_fisicodefectotii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='procesado',
            field=models.IntegerField(choices=[(1, 'Lavado'), (2, 'Natural'), (3, 'Honey')], default=2, verbose_name='Procesado'),
        ),
    ]
