# Generated by Django 4.0 on 2022-08-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_muestra_procesado'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='ciclo',
            field=models.IntegerField(blank=True, choices=[(1, '2019-2020'), (2, '2020-2021'), (3, '2021-2022')], null=True, verbose_name='Ciclo'),
        ),
    ]
