# Generated by Django 4.0 on 2022-08-04 17:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_muestra_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='caracteristicas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Derrame'), (2, 'Olor no característico'), (3, 'Empaque roto'), (4, 'Buen estado')], max_length=7, verbose_name='Caracteristicas'),
        ),
    ]
