# Generated by Django 4.0 on 2022-08-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_organizacion_tipo_org'),
        ('analisis', '0005_alter_muestra_caracteristicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('oAnalisis', models.IntegerField(choices=[(1, 'Seguimiento Cooperativa'), (2, 'Concurso'), (3, 'Solicitud del Productor'), (4, 'Solicitud del Comprador')], default=1)),
                ('fechaAnalisis', models.DateField(blank=True)),
                ('PuntajeFinal', models.FloatField(blank=True, default=0.0)),
                ('estado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente')], default=2)),
                ('fkFisico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AFisico', to='analisis.fisico', verbose_name='Fisico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='analizado',
        ),
        migrations.AddField(
            model_name='muestra',
            name='repetir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente')], default=2),
        ),
        migrations.CreateModel(
            name='Sensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('cAgua', models.FloatField(blank=True, default=0.0)),
                ('nTueste', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=1)),
                ('fragancia', models.FloatField(blank=True, default=0.0)),
                ('pAroma', models.FloatField(blank=True, default=0.0)),
                ('seco', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=1)),
                ('espuma', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=1)),
                ('pSabor', models.FloatField(blank=True, default=0.0)),
                ('remanente', models.FloatField(blank=True, default=0.0)),
                ('pUniformidad', models.FloatField(blank=True, default=0.0)),
                ('cUniformidad', models.IntegerField(default=0)),
                ('pTLimpia', models.FloatField(blank=True, default=0.0)),
                ('cTLimpia', models.IntegerField(default=0)),
                ('pDulzor', models.FloatField(blank=True, default=0.0)),
                ('cDulzor', models.IntegerField(default=0)),
                ('acidez', models.FloatField(blank=True, default=0.0)),
                ('iAcidez', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=2)),
                ('cuerpo', models.FloatField(blank=True, default=0.0)),
                ('iCuerpo', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=2)),
                ('balance', models.FloatField(blank=True, default=0.0)),
                ('comentario', models.TextField(blank=True, max_length=254, verbose_name='Observaciones')),
                ('pCatador', models.FloatField(blank=True, default=0.0)),
                ('castigo', models.FloatField(blank=True, default=0.0)),
                ('pFinal', models.FloatField(blank=True, default=0.0)),
                ('fechaSensorial', models.DateField(auto_now_add=True)),
                ('aroma', models.ManyToManyField(blank=True, related_name='AAroma', to='analisis.Aroma', verbose_name='Aromas')),
                ('fkCatador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatadorSensorial', to='autenticacion.colaborador', verbose_name='CatadorSensorial')),
                ('fkMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sensorial', to='analisis.muestra', verbose_name='Muestra')),
                ('sabor', models.ManyToManyField(blank=True, related_name='ASabor', to='analisis.Sabor', verbose_name='Sabores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('fechaConciliacion', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente')], default=2)),
                ('fkAnalisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAnalisis', to='analisis.analisis', verbose_name='Analisis')),
                ('fkCFisico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CFisico', to='analisis.fisico', verbose_name='Fisico')),
                ('fkCSensorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CSensorial', to='analisis.sensorial', verbose_name='Sensorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkMuestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AMuestra', to='analisis.muestra', verbose_name='Muestra'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkSensorial',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ASensorial', to='analisis.sensorial', verbose_name='Sensorial'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkTecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ATecnico', to='autenticacion.colaborador', verbose_name='Tecnico'),
        ),
    ]
