# Generated by Django 4.0 on 2022-08-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0006_analisis_remove_muestra_analizado_muestra_repetir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamizado',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idTamizado', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameTamizado', models.CharField(max_length=64, verbose_name='Tamizado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fisico',
            name='temp',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada')], default=2),
        ),
        migrations.RemoveField(
            model_name='analisis',
            name='fkFisico',
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkFisico',
            field=models.ManyToManyField(blank=True, related_name='AFisico', to='analisis.Fisico', verbose_name='Fisico'),
        ),
        migrations.RemoveField(
            model_name='analisis',
            name='fkSensorial',
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkSensorial',
            field=models.ManyToManyField(blank=True, related_name='ASensorial', to='analisis.Sensorial', verbose_name='Sensorial'),
        ),
        migrations.AlterField(
            model_name='conciliacion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada')], default=2),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada')], default=2),
        ),
        migrations.CreateModel(
            name='FisicoTamizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('pesoGranos', models.FloatField(blank=True, default=0.0)),
                ('porGranos', models.FloatField(blank=True, default=0.0)),
                ('fkFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FisicoTamizado', to='analisis.fisico', verbose_name='Fisico')),
                ('fkTamizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tamizado', to='analisis.tamizado', verbose_name='Tamizado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
