# Generated by Django 4.0 on 2022-09-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0008_alter_analisis_estado_alter_conciliacion_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisico',
            old_name='pBroca',
            new_name='porDefectos',
        ),
        migrations.RemoveField(
            model_name='fisico',
            name='pMancha',
        ),
        migrations.RemoveField(
            model_name='fisico',
            name='pRendimiento',
        ),
    ]
