# Generated by Django 4.0 on 2022-09-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0010_fisico_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisicodefectoti',
            name='defectos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fisicodefectoti',
            name='encontrados',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fisicodefectotii',
            name='defectos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fisicodefectotii',
            name='encontrados',
            field=models.FloatField(default=0),
        ),
    ]
