# Generated by Django 4.0 on 2022-09-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0011_alter_fisicodefectoti_defectos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorial',
            name='pAroma',
        ),
    ]
