# Generated by Django 4.0 on 2022-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0012_remove_sensorial_paroma'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisicotamizado',
            name='pesoTotal',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='fisicotamizado',
            name='porTotal',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
