# Generated by Django 4.0 on 2022-10-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0014_remove_fisicotamizado_pesototal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciliacion',
            name='fkAnalisis',
        ),
        migrations.RemoveField(
            model_name='conciliacion',
            name='fkCFisico',
        ),
        migrations.DeleteModel(
            name='Analisis',
        ),
    ]
