# Generated by Django 4.0 on 2022-10-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_colaborador_firma'),
        ('analisis', '0015_remove_conciliacion_fkanalisis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorial',
            name='fkCatador',
        ),
        migrations.AddField(
            model_name='sensorial',
            name='fkCatador',
            field=models.ManyToManyField(related_name='CatadorSensorial', to='autenticacion.Colaborador', verbose_name='CatadorSensorial'),
        ),
        migrations.RemoveField(
            model_name='sensorial',
            name='fkMuestra',
        ),
        migrations.AddField(
            model_name='sensorial',
            name='fkMuestra',
            field=models.ManyToManyField(related_name='Sensorial', to='analisis.Muestra', verbose_name='Muestra'),
        ),
    ]
