# Generated by Django 4.0 on 2022-10-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_colaborador_firma'),
        ('analisis', '0016_remove_sensorial_fkcatador_sensorial_fkcatador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorial',
            name='fkCatador',
        ),
        migrations.AddField(
            model_name='sensorial',
            name='fkCatador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CatadorSensorial', to='autenticacion.colaborador', verbose_name='CatadorSensorial'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sensorial',
            name='fkMuestra',
        ),
        migrations.AddField(
            model_name='sensorial',
            name='fkMuestra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Sensorial', to='analisis.muestra', verbose_name='Muestra'),
            preserve_default=False,
        ),
    ]
