# Generated by Django 4.0 on 2022-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0017_remove_sensorial_fkcatador_sensorial_fkcatador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorial',
            name='iAcidez',
            field=models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], default=2),
        ),
        migrations.AlterField(
            model_name='sensorial',
            name='iCuerpo',
            field=models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], default=2),
        ),
    ]
