# Generated by Django 4.0 on 2022-07-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('tipoUser', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Jefe de Laboratorio'), (3, 'Digitador de Laboratorio'), (4, 'Analista de Laboratorio'), (5, 'Jefe de Cooperativa'), (6, 'Digitador de Cooperativa'), (7, 'Analista de Cooperativa'), (8, 'Hibrido Cooperativa')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('id_org', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_org', models.CharField(max_length=64)),
                ('tipo_org', models.IntegerField(choices=[(1, 'Cooperativa'), (2, 'Laboratorio')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
