# Generated by Django 4.0 on 2022-07-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registros', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgMunicipio', to='registros.municipio'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacionColab', to='autenticacion.organizacion'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='auth.user'),
        ),
    ]
