# Generated by Django 4.0 on 2022-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tipo_org',
            field=models.IntegerField(choices=[(1, 'Cooperativa'), (2, 'Laboratorio'), (3, 'Adminstración')], default=1),
        ),
    ]
