# Generated by Django 4.0 on 2022-10-13 01:23

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_organizacion_tipo_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='firma',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
