# Generated by Django 4.0 on 2023-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_colaborador_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='nameLogo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre del logo'),
        ),
    ]
