# Generated by Django 4.0 on 2023-03-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_certificacion_nameimg'),
        ('autenticacion', '0005_organizacion_namelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('id_sede', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_sede', models.CharField(max_length=64)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sedeMunicipio', to='registros.municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizacion',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='sedeOrg', to='autenticacion.Sede'),
        ),
    ]
