# Generated by Django 4.0 on 2022-07-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCert', models.CharField(max_length=64, verbose_name='Certificación')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('idCom', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Comunidad')),
                ('nameCom', models.CharField(max_length=64, verbose_name='Nombre Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDpto', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Dpto')),
                ('nameDpto', models.CharField(max_length=64, verbose_name='Nombre Dpto')),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('idFinca', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Finca')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('nameFinca', models.CharField(max_length=64, verbose_name='nameFinca')),
                ('area', models.FloatField(default=0.0)),
                ('estado', models.IntegerField(default=1)),
                ('fkCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincaComunidad', to='registros.comunidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMun', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID_Municipio')),
                ('nameMun', models.CharField(max_length=64, verbose_name='Nombre Municipio')),
                ('fkdpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='registros.departamento', verbose_name='ID_Dpto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Pais')),
                ('namePais', models.CharField(max_length=64, verbose_name='Nombre Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameVariedad', models.CharField(max_length=64, verbose_name='TipoCafe')),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('idProd', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Productor')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('firstnameProd', models.CharField(max_length=64, verbose_name='fnameProductor')),
                ('lastnameProd', models.CharField(max_length=64, verbose_name='lnameProductor')),
                ('fechaNac', models.DateField(null=True)),
                ('estado', models.IntegerField(default=1)),
                ('fkMun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodMunicipio', to='registros.municipio')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgProductor', to='autenticacion.organizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idLote', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Lote')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('nameLote', models.CharField(max_length=64, verbose_name='nameLote')),
                ('area', models.FloatField(default=0.0)),
                ('altitud', models.FloatField(default=0.0)),
                ('estado', models.IntegerField(default=1)),
                ('fkCert', models.ManyToManyField(blank=True, related_name='Certificaciones', to='registros.Certificacion')),
                ('fkFinca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoteFinca', to='registros.finca', verbose_name='Finca')),
                ('fkVar', models.ManyToManyField(blank=True, related_name='Variedades', to='registros.Variedad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='fkProd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincaProductor', to='registros.productor'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fkPais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisDpto', to='registros.pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='fkMun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidadMunicipio', to='registros.municipio'),
        ),
    ]
