# Generated by Django 4.0 on 2022-08-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='unidad',
            field=models.CharField(choices=[('Mz', 'Mz'), ('Ha', 'Ha')], default='Mz', max_length=4),
        ),
        migrations.AddField(
            model_name='lote',
            name='unidad',
            field=models.CharField(choices=[('Mz', 'Mz'), ('Ha', 'Ha')], default='Mz', max_length=4),
        ),
    ]
