# Generated by Django 4.0 on 2023-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_finca_unidad_lote_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='nameImg',
            field=models.CharField(default='', max_length=64, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
