# Generated by Django 4.0 on 2023-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_certificacion_nameimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='codeProd',
            field=models.CharField(blank=True, max_length=64, verbose_name='codeProductor'),
        ),
    ]
