# Generated by Django 4.0 on 2023-04-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_productor_codeprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
