# Generated by Django 4.0 on 2022-08-08 23:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0003_alter_organizacion_tipo_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('oAnalisis', models.IntegerField(choices=[(1, 'Seguimiento Cooperativa'), (2, 'Concurso'), (3, 'Solicitud del Productor'), (4, 'Solicitud del Comprador')], default=1)),
                ('fechaAnalisis', models.DateField(blank=True)),
                ('PuntajeFinal', models.FloatField(blank=True, default=0.0)),
                ('estado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idAroma', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameAroma', models.CharField(max_length=64, verbose_name='Aroma')),
                ('nivelAroma', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1)),
                ('pI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IPAroma', to='laboratorios.aroma', verbose_name='Padre Nivel I')),
                ('pII', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IIPAroma', to='laboratorios.aroma', verbose_name='Padre Nivel II')),
                ('pIII', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IIIPAroma', to='laboratorios.aroma', verbose_name='Padre Nivel III')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectoT1',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idDefecto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameDefecto', models.CharField(max_length=64, verbose_name='Defecto')),
                ('granosNecesarios', models.IntegerField(verbose_name='Granos Necesarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectoT2',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idDefecto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameDefecto', models.CharField(max_length=64, verbose_name='Defecto')),
                ('granosNecesarios', models.IntegerField(verbose_name='Granos Necesarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('pDefectos', models.FloatField(blank=True, default=0.0)),
                ('pRendimiento', models.FloatField(blank=True, default=0.0)),
                ('pMancha', models.FloatField(blank=True, default=0.0)),
                ('pBroca', models.FloatField(blank=True, default=0.0)),
                ('temp', models.FloatField(blank=True, default=0.0)),
                ('fechaFisico', models.DateField(auto_now_add=True)),
                ('fkCatador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LCatadorFisico', to='autenticacion.colaborador', verbose_name='CatadorFisico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('idMuestra', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Lote')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('ordenTrabajo', models.IntegerField(null=True, unique=True, verbose_name='Orden de Trabajo')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Recepción')),
                ('codigoPais', models.CharField(default='017', max_length=4, verbose_name='Código de País')),
                ('exportador', models.CharField(default='0000', max_length=64, verbose_name='Exportador')),
                ('lote', models.IntegerField(default=0, verbose_name='Lote')),
                ('peso', models.CharField(choices=[('100', '100'), ('300', '300'), ('350', '350'), ('500', '500')], default='500', max_length=4)),
                ('tipo', models.IntegerField(choices=[(1, 'Cafe Pergamino'), (2, 'Cafe Oro')], verbose_name='Tipo de Muestra')),
                ('caracteristicas', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Derrame'), (2, 'Olor no característico'), (3, 'Empaque roto'), (4, 'Buen estado')], max_length=7, verbose_name='Caracteristicas')),
                ('rMuestra', models.IntegerField(default=0)),
                ('procesos', models.IntegerField(choices=[(1, 'Fisico'), (2, 'Sensorial'), (3, 'Ambos')], verbose_name='Procesos a aplicar')),
                ('procesado', models.IntegerField(choices=[(1, 'Lavado'), (2, 'Natural'), (3, 'Honey')], default=2, verbose_name='Procesado')),
                ('ciclo', models.IntegerField(blank=True, choices=[(1, '2019-2020'), (2, '2020-2021'), (3, '2021-2022')], null=True, verbose_name='Ciclo')),
                ('observaciones', models.TextField(blank=True, max_length=254, verbose_name='Observaciones')),
                ('estado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada')], default=2)),
                ('repetir', models.BooleanField(default=False)),
                ('fkOrg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LOrgMuestra', to='autenticacion.organizacion', verbose_name='Organización')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idSabor', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameSabor', models.CharField(max_length=64, verbose_name='Sabor')),
                ('nivelSabor', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1)),
                ('pI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IPSabor', to='laboratorios.sabor', verbose_name='Padre Nivel I')),
                ('pII', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IIPSabor', to='laboratorios.sabor', verbose_name='Padre Nivel II')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tamizado',
            fields=[
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('idTamizado', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nameTamizado', models.CharField(max_length=64, verbose_name='Tamizado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('cAgua', models.FloatField(blank=True, default=0.0)),
                ('nTueste', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=1)),
                ('fragancia', models.FloatField(blank=True, default=0.0)),
                ('pAroma', models.FloatField(blank=True, default=0.0)),
                ('seco', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=1)),
                ('espuma', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=1)),
                ('pSabor', models.FloatField(blank=True, default=0.0)),
                ('remanente', models.FloatField(blank=True, default=0.0)),
                ('pUniformidad', models.FloatField(blank=True, default=0.0)),
                ('cUniformidad', models.IntegerField(default=0)),
                ('pTLimpia', models.FloatField(blank=True, default=0.0)),
                ('cTLimpia', models.IntegerField(default=0)),
                ('pDulzor', models.FloatField(blank=True, default=0.0)),
                ('cDulzor', models.IntegerField(default=0)),
                ('acidez', models.FloatField(blank=True, default=0.0)),
                ('iAcidez', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=2)),
                ('cuerpo', models.FloatField(blank=True, default=0.0)),
                ('iCuerpo', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')], default=2)),
                ('balance', models.FloatField(blank=True, default=0.0)),
                ('comentario', models.TextField(blank=True, max_length=254, verbose_name='Observaciones')),
                ('pCatador', models.FloatField(blank=True, default=0.0)),
                ('castigo', models.FloatField(blank=True, default=0.0)),
                ('pFinal', models.FloatField(blank=True, default=0.0)),
                ('fechaSensorial', models.DateField(auto_now_add=True)),
                ('aroma', models.ManyToManyField(blank=True, related_name='AAroma', to='laboratorios.Aroma', verbose_name='Aromas')),
                ('fkCatador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LCatadorSensorial', to='autenticacion.colaborador', verbose_name='CatadorSensorial')),
                ('fkMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LSensorial', to='laboratorios.muestra', verbose_name='Muestra')),
                ('sabor', models.ManyToManyField(blank=True, related_name='ASabor', to='laboratorios.Sabor', verbose_name='Sabores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FisicoTamizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('pesoGranos', models.FloatField(blank=True, default=0.0)),
                ('porGranos', models.FloatField(blank=True, default=0.0)),
                ('fkFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FisicoTamizado', to='laboratorios.fisico', verbose_name='Fisico')),
                ('fkTamizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tamizado', to='laboratorios.tamizado', verbose_name='Tamizado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FisicoDefectoTII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('encontrados', models.IntegerField(default=0)),
                ('defectos', models.IntegerField(default=0)),
                ('pesoDefecto', models.FloatField(blank=True, default=0.0)),
                ('porDefecto', models.FloatField(blank=True, default=0.0)),
                ('fkDefecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DefectoT2', to='laboratorios.defectot2', verbose_name='Defecto')),
                ('fkFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FisicoDefectoTII', to='laboratorios.fisico', verbose_name='Fisico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FisicoDefectoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('encontrados', models.IntegerField(default=0)),
                ('defectos', models.IntegerField(default=0)),
                ('pesoDefecto', models.FloatField(blank=True, default=0.0)),
                ('porDefecto', models.FloatField(blank=True, default=0.0)),
                ('fkDefecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DefectoT1', to='laboratorios.defectot1', verbose_name='Defecto')),
                ('fkFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FisicoDefectoTI', to='laboratorios.fisico', verbose_name='Fisico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fisico',
            name='fkMuestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LFsico', to='laboratorios.muestra', verbose_name='Muestra'),
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='Fecha de creación')),
                ('last_modified', models.DateTimeField(editable=False, verbose_name='Última modificación')),
                ('fechaConciliacion', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada')], default=2)),
                ('fkAnalisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAnalisis', to='laboratorios.analisis', verbose_name='Analisis')),
                ('fkCFisico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CFisico', to='laboratorios.fisico', verbose_name='Fisico')),
                ('fkCSensorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CSensorial', to='laboratorios.sensorial', verbose_name='Sensorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkFisico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='LAFisico', to='laboratorios.fisico', verbose_name='Fisico'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkMuestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LAMuestra', to='laboratorios.muestra', verbose_name='Muestra'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkSensorial',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='LASensorial', to='laboratorios.sensorial', verbose_name='Sensorial'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='fkTecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LATecnico', to='autenticacion.colaborador', verbose_name='Tecnico'),
        ),
    ]
