# Generated by Django 4.0 on 2022-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada'), (10, 'Fisico Listo'), (11, 'Sensorial Listo'), (12, 'Ambos Listo')], default=2),
        ),
        migrations.AlterField(
            model_name='conciliacion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada'), (10, 'Fisico Listo'), (11, 'Sensorial Listo'), (12, 'Ambos Listo')], default=2),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Completado'), (2, 'Pendiente Ambos'), (3, 'Pendiente Fisico'), (4, 'Pendiente Sensorial'), (5, 'Pendiente Conciliacion'), (6, 'Conciliada'), (7, 'Cancelada'), (8, 'Pendiente'), (9, 'Rechazada'), (10, 'Fisico Listo'), (11, 'Sensorial Listo'), (12, 'Ambos Listo')], default=2),
        ),
    ]
