# Generated by Django 4.0 on 2022-09-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0003_rename_pbroca_fisico_pordefectos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='humedad',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
