# Generated by Django 4.0 on 2022-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0006_fisicotamizado_pesototal_fisicotamizado_portotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisicotamizado',
            name='pesoTotal',
        ),
        migrations.RemoveField(
            model_name='fisicotamizado',
            name='porTotal',
        ),
        migrations.AddField(
            model_name='fisico',
            name='pesoTotalTamiz',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='fisico',
            name='porTotalTamiz',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
