# Generated by Django 4.0 on 2022-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0008_alter_sensorial_iacidez_alter_sensorial_icuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='rendimiento',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
