# Generated by Django 4.0 on 2023-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0009_fisico_rendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorial',
            name='espuma',
            field=models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], default=1),
        ),
        migrations.AlterField(
            model_name='sensorial',
            name='nTueste',
            field=models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], default=1),
        ),
        migrations.AlterField(
            model_name='sensorial',
            name='seco',
            field=models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], default=1),
        ),
    ]
