# Generated by Django 4.0 on 2023-03-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_sede_organizacion_sedes'),
        ('laboratorios', '0010_alter_sensorial_espuma_alter_sensorial_ntueste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='sedeAnalisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LABSedeAnalisis', to='autenticacion.sede', verbose_name='Sede de Analisis'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='sedeRecepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LABSedeMuestra', to='autenticacion.sede', verbose_name='Sede de Recepción'),
        ),
    ]
