# Generated by Django 4.0 on 2023-03-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0011_muestra_sedeanalisis_muestra_sederecepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='pesoTamiz',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
